<?php

return [
    'custom_order_list_report' => 'Custom Order List Report',
    'report_date' => 'Report Date',
    'customer_name' => 'Customer Name',
    'product_name' => 'Product Name',
    'quantity' => 'Quantity',
    'report_summary' => 'Report Summary',
    'total_orders' => 'Total Orders',
    'total_quantity' => 'Total Product Quantity',
    'report_creation_date' => 'Report Creation Date',
    'pcs' => 'pcs',
    'auto_generated_report' => 'This report has been automatically generated by the system.',
    'pay_desc' => 'Payment Description',
    'delivery_date' => 'Delivery Date',
    'phone' => 'Phone Number'


];
