<?php

return [
    'smartbakery_freezer_report' => 'SmartBakery Freezer Report',
    'freezer_report' => 'Freezer Report',
    'report_date' => 'Report Date',
    'report_summary' => 'Report Summary',
    'freezer_summary_text' => 'This report shows the defined cabinets and cooling temperatures in the smartBakery system.',
    'freezer_name' => 'Freezer Name',
    'working_degree' => 'Working Degree',
    'description' => 'Description',
    'smartbakery_management_system' => 'SmartBakery Management System - Automatic Report',
    'auto_generated_report' => 'This report has been automatically generated by the system.',
];
