<?php

return [

    'report_title' => 'Product Sales and Waste Report',
    'company_name' => 'Company Name',
    'company_address' => 'Company Address, City/District',
    'phone' => 'Phone',
    'report_date' => 'Report Date',
    'date_range' => 'Date Range',
    'summary' => 'Summary Information',
    'total_production' => 'Total Production',
    'total_sales' => 'Total Sales',
    'total_waste' => 'Total Waste',
    'product_name' => 'Product Name',
    'production' => 'Production',
    'sales' => 'Sales',
    'waste' => 'Waste',
    'carryover' => 'Carryover to Next Day',
    'piece' => 'pcs',
    'generated_on' => 'This report was automatically generated by the system on :date.',
    'rights_reserved' => 'All rights reserved.',
    'page' => 'Page',
];
